### PR TITLE
Moved to redis totally - ahangarha

### LINKED ISSUE #13: Migrate db to redis

### PR DESCRIPTION
**Pull request by ahangarha**
FIX #13

By this commit, I have replaced all the datasets from arrays into redis.
I have checked the functionality of the bot based on sample dataset I
had before.

### CODE REVIEW

**Comment by ahangarha** [comment]
I am totally confused. I add blank line at the end of `db.py`, my local pep8/pycodestyle gives me this error:

    db.py:95:1: W391 blank line at end of file

I remove it, travis gives me this error:

    ./ahangarha_startingup2017_bot/db.py:94:28: W292 no newline at end of file

What the hell!!!

**Review by masihtehrani — CHANGES_REQUESTED** [review]
please one commit for one issue
and this issue have problem with travis

**Comment by gitygity** [comment]
yes . when i modify my code , i saw this problem. dont pay attention to this error 'no newline at end of file' . you should remove blank line end of your codes.

**Review by gitygity — APPROVED** [review]

**Comment by ahangarha** [comment]
I close this PR and will send a new one soon

**Pull request closed without merging**
